export const appUiBasics = {
  id: 'app-ui-basics',
  titleSv: 'App UI: grunder',
  titleZh: '应用界面基础',
  pinyin: 'yìngyòng jièmiàn jīchǔ',
  descriptionSv: 'Börja här. Du lär dig de ord som appen själv använder, och gränssnittet blir gradvis kinesiskt.',
  order: 0,
  lessons: [
    {
      id: 'first-characters',
      titleSv: 'Första tecken',
      descriptionSv: 'En mjuk start med korta en-teckenord innan längre knapptexter.',
      unlocksUiKeys: ['term.word', 'feedback.correct', 'feedback.wrong'],
      unlocksExerciseTypes: ['type-pinyin'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-chinese', sv: 'kinesiska / Kina', hanzi: '中', pinyin: 'zhōng', notesSv: 'Syns i appikonen. I ord som 中文 betyder det kinesiska språket.' },
        { id: 'ui-text', sv: 'text / språk', hanzi: '文', pinyin: 'wén', notesSv: 'Används i 中文: kinesiska språket.' },
        { id: 'ui-word', sv: 'ord', hanzi: '词', pinyin: 'cí', uiKey: 'term.word' },
        { id: 'ui-correct', sv: 'rätt', hanzi: '对', pinyin: 'duì', uiKey: 'feedback.correct' },
        { id: 'ui-wrong', sv: 'fel', hanzi: '错', pinyin: 'cuò', uiKey: 'feedback.wrong' },
      ],
    },
    {
      id: 'start-button',
      titleSv: 'Startknappen',
      descriptionSv: 'Bygg upp 开始 från två enklare tecken.',
      unlocksUiKeys: ['action.start'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-open', sv: 'öppna / starta', hanzi: '开', pinyin: 'kāi', notesSv: 'Första tecknet i 开始.' },
        { id: 'ui-begin-char', sv: 'börja', hanzi: '始', pinyin: 'shǐ', notesSv: 'Andra tecknet i 开始.' },
        {
          id: 'ui-start',
          sv: 'starta / börja',
          hanzi: '开始',
          pinyin: 'kāishǐ',
          uiKey: 'action.start',
          notesSv: 'Vanligt för Start eller Börja.',
          components: [
            { hanzi: '开', pinyin: 'kāi', sv: 'öppna / starta' },
            { hanzi: '始', pinyin: 'shǐ', sv: 'börja' },
          ],
        },
      ],
    },
    {
      id: 'home-button',
      titleSv: 'Hem och startsida',
      descriptionSv: 'Först tecknen, sedan hela ordet 首页.',
      unlocksUiKeys: ['nav.home'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-first-page', sv: 'första / huvud-', hanzi: '首', pinyin: 'shǒu', notesSv: 'Första tecknet i 首页.' },
        { id: 'ui-page', sv: 'sida', hanzi: '页', pinyin: 'yè', notesSv: 'Andra tecknet i 首页.' },
        {
          id: 'ui-home',
          sv: 'hem / startsida',
          hanzi: '首页',
          pinyin: 'shǒuyè',
          uiKey: 'nav.home',
          notesSv: 'Betyder ungefär första sida/startsida.',
          components: [
            { hanzi: '首', pinyin: 'shǒu', sv: 'första / huvud-' },
            { hanzi: '页', pinyin: 'yè', sv: 'sida' },
          ],
        },
      ],
    },
    {
      id: 'back-button',
      titleSv: 'Tillbaka',
      descriptionSv: 'Först 回, sedan knappordet 返回.',
      unlocksUiKeys: ['action.back'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-return-char', sv: 'återvända / tillbaka', hanzi: '回', pinyin: 'huí', notesSv: 'Används i flera ord som handlar om att gå tillbaka.' },
        {
          id: 'ui-back',
          sv: 'tillbaka',
          hanzi: '返回',
          pinyin: 'fǎnhuí',
          uiKey: 'action.back',
          notesSv: 'Vanlig knapp för att gå tillbaka.',
          components: [
            { hanzi: '返', pinyin: 'fǎn', sv: 'återvända' },
            { hanzi: '回', pinyin: 'huí', sv: 'tillbaka / åter' },
          ],
        },
      ],
    },
    {
      id: 'settings-button',
      titleSv: 'Inställningar',
      descriptionSv: 'Först 设 och 置, sedan 设置.',
      unlocksUiKeys: ['settings.title'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-set-up-char', sv: 'ställa in / ordna', hanzi: '设', pinyin: 'shè', notesSv: 'Första tecknet i 设置.' },
        { id: 'ui-place-char', sv: 'placera / sätta', hanzi: '置', pinyin: 'zhì', notesSv: 'Andra tecknet i 设置.' },
        {
          id: 'ui-settings',
          sv: 'inställningar',
          hanzi: '设置',
          pinyin: 'shèzhì',
          uiKey: 'settings.title',
          notesSv: 'Mycket vanlig menytext i appar.',
          components: [
            { hanzi: '设', pinyin: 'shè', sv: 'ställa in' },
            { hanzi: '置', pinyin: 'zhì', sv: 'placera / sätta' },
          ],
        },
      ],
    },
    {
      id: 'app-hanhan-name',
      titleSv: 'Appens namn: 汉汉',
      descriptionSv: 'Tecknet 汉 för kinesiska språket, och hur det blir appens namn i reduplikation.',
      unlocksUiKeys: ['app.title', 'nav.about'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-han-char', sv: 'kinesiska (språk)', hanzi: '汉', pinyin: 'hàn', notesSv: 'En förkortning för kinesiska språket, som i 汉语.' },
        {
          id: 'ui-hanhan-name',
          sv: 'appens namn',
          hanzi: '汉汉',
          pinyin: 'hàn hàn',
          uiKey: 'app.title',
          notesSv: 'Appens namn: Hàn betyder kinesiska språket. Fördubblat som en vänlig smekform, på samma sätt som andra appar.',
          components: [
            { hanzi: '汉', pinyin: 'hàn', sv: 'kinesiska språket' },
          ],
        },
        { id: 'ui-about-char', sv: 'stänga / relatera', hanzi: '关', pinyin: 'guān', notesSv: 'Första tecknet i 关于.' },
        { id: 'ui-about-word', sv: 'om / angående', hanzi: '关于', pinyin: 'guānyú', components: [{ hanzi: '关', pinyin: 'guān', sv: 'relatera' }] },
        {
          id: 'ui-about-hanhan',
          sv: 'Om HànHàn',
          hanzi: '关于汉汉',
          pinyin: 'guānyú hàn hàn',
          uiKey: 'nav.about',
          notesSv: 'Vanlig rubrik för en Om-sida: 关于 betyder om eller angående.',
          components: [
            { hanzi: '关于', pinyin: 'guānyú', sv: 'om / angående' },
            { hanzi: '汉汉', pinyin: 'hàn hàn', sv: 'HànHàn' },
          ],
        },
      ],
    },
    {
      id: 'review-actions',
      titleSv: 'Repetera',
      descriptionSv: 'Bara repetitionsknappen, så lektionen blir kortare.',
      unlocksUiKeys: ['action.review', 'review.title'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-practice-study-char', sv: 'öva / studera', hanzi: '习', pinyin: 'xí', notesSv: 'Andra tecknet i 复习.' },
        { id: 'ui-review', sv: 'repetera', hanzi: '复习', pinyin: 'fùxí', uiKey: 'action.review', components: [{ hanzi: '习', pinyin: 'xí', sv: 'öva / studera' }] },
        { id: 'ui-review-title', sv: 'repetition', hanzi: '复习', pinyin: 'fùxí', uiKey: 'review.title', components: [{ hanzi: '习', pinyin: 'xí', sv: 'öva / studera' }] },
      ],
    },
    {
      id: 'learn-actions',
      titleSv: 'Lära och öva',
      descriptionSv: 'Lära och öva, med ett gemensamt tecken.',
      unlocksUiKeys: ['action.learn', 'action.practice'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-study-char', sv: 'lära / studera', hanzi: '学', pinyin: 'xué', notesSv: 'Första tecknet i 学习.' },
        { id: 'ui-learn', sv: 'lära sig / studera', hanzi: '学习', pinyin: 'xuéxí', uiKey: 'action.learn', components: [{ hanzi: '学', pinyin: 'xué', sv: 'lära / studera' }, { hanzi: '习', pinyin: 'xí', sv: 'öva' }] },
        { id: 'ui-train-char', sv: 'träna', hanzi: '练', pinyin: 'liàn', notesSv: 'Första tecknet i 练习.' },
        { id: 'ui-practice', sv: 'öva', hanzi: '练习', pinyin: 'liànxí', uiKey: 'action.practice', components: [{ hanzi: '练', pinyin: 'liàn', sv: 'träna' }, { hanzi: '习', pinyin: 'xí', sv: 'öva' }] },
      ],
    },
    {
      id: 'continue-lesson',
      titleSv: 'Fortsätt och lektion',
      descriptionSv: 'Två vanliga ord i lektionsflödet.',
      unlocksUiKeys: ['action.continue', 'lesson.title', 'lesson.complete', 'status.inProgress', 'status.incomplete'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-continue-char', sv: 'fortsätta', hanzi: '续', pinyin: 'xù', notesSv: 'Ett tecken i 继续.' },
        { id: 'ui-continue', sv: 'fortsätt', hanzi: '继续', pinyin: 'jìxù', uiKey: 'action.continue', components: [{ hanzi: '续', pinyin: 'xù', sv: 'fortsätta' }] },
        { id: 'ui-class-char', sv: 'lektion', hanzi: '课', pinyin: 'kè', notesSv: 'Första tecknet i 课程.' },
        { id: 'ui-lesson', sv: 'lektion / kurs', hanzi: '课程', pinyin: 'kèchéng', uiKey: 'lesson.title', components: [{ hanzi: '课', pinyin: 'kè', sv: 'lektion' }, { hanzi: '程', pinyin: 'chéng', sv: 'kurs / process' }] },
        { id: 'ui-complete-char1', sv: 'färdig / komplett', hanzi: '完', pinyin: 'wán', notesSv: 'Första tecknet i 完成.' },
        { id: 'ui-complete-char2', sv: 'bli / åstadkomma', hanzi: '成', pinyin: 'chéng', notesSv: 'Andra tecknet i 完成.' },
        { id: 'ui-complete', sv: 'klar / slutförd', hanzi: '完成', pinyin: 'wánchéng', uiKey: 'lesson.complete', components: [{ hanzi: '完', pinyin: 'wán', sv: 'färdig / komplett' }, { hanzi: '成', pinyin: 'chéng', sv: 'bli / åstadkomma' }] },
        { id: 'ui-progressing', sv: 'pågående', hanzi: '进行中', pinyin: 'jìnxíng zhōng', uiKey: 'status.inProgress', components: [{ hanzi: '中', pinyin: 'zhōng', sv: 'i / mitten' }] },
        { id: 'ui-not-yet-char', sv: 'inte ännu', hanzi: '未', pinyin: 'wèi', notesSv: 'Första tecknet i 未完成.' },
        { id: 'ui-incomplete', sv: 'ej klar', hanzi: '未完成', pinyin: 'wèi wánchéng', uiKey: 'status.incomplete', components: [{ hanzi: '未', pinyin: 'wèi', sv: 'inte ännu' }, { hanzi: '完成', pinyin: 'wánchéng', sv: 'klar / slutförd' }] },
      ],
    },
    {
      id: 'answers-feedback',
      titleSv: 'Svar och feedback',
      descriptionSv: 'Svar, visa svar och nästa.',
      unlocksUiKeys: ['term.answer', 'action.next', 'action.showAnswer'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-answer-char', sv: 'svara', hanzi: '答', pinyin: 'dá', notesSv: 'Första tecknet i 答案.' },
        { id: 'ui-answer', sv: 'svar', hanzi: '答案', pinyin: 'dá’àn', uiKey: 'term.answer', components: [{ hanzi: '答', pinyin: 'dá', sv: 'svara' }, { hanzi: '案', pinyin: 'àn', sv: 'förslag / fall' }] },
        { id: 'ui-show-char1', sv: 'synas / framträda', hanzi: '显', pinyin: 'xiǎn', notesSv: 'Första tecknet i 显示.' },
        { id: 'ui-show-char2', sv: 'visa / indikera', hanzi: '示', pinyin: 'shì', notesSv: 'Andra tecknet i 显示.' },
        { id: 'ui-show-word', sv: 'visa', hanzi: '显示', pinyin: 'xiǎnshì', notesSv: 'Första delen av 显示答案. Används ofta i appar för att visa något.', components: [{ hanzi: '显', pinyin: 'xiǎn', sv: 'synas / framträda' }, { hanzi: '示', pinyin: 'shì', sv: 'visa / indikera' }] },
        { id: 'ui-show-answer', sv: 'visa svar', hanzi: '显示答案', pinyin: 'xiǎnshì dá’àn', uiKey: 'action.showAnswer', components: [{ hanzi: '显示', pinyin: 'xiǎnshì', sv: 'visa' }, { hanzi: '答案', pinyin: 'dá’àn', sv: 'svar' }] },
        { id: 'ui-down-next-char', sv: 'nästa / ned', hanzi: '下', pinyin: 'xià', notesSv: 'Första tecknet i 下一个.' },
        { id: 'ui-one-char', sv: 'ett', hanzi: '一', pinyin: 'yī', notesSv: 'Andra tecknet i 下一个. Grundläggande räkneord.' },
        { id: 'ui-measure-char', sv: 'styck (måttsord)', hanzi: '个', pinyin: 'ge', notesSv: 'Tredje tecknet i 下一个. Ett vanligt måttsord.' },
        { id: 'ui-next', sv: 'nästa', hanzi: '下一个', pinyin: 'xià yí ge', uiKey: 'action.next', components: [{ hanzi: '下', pinyin: 'xià', sv: 'nästa / ned' }, { hanzi: '一', pinyin: 'yī', sv: 'ett' }, { hanzi: '个', pinyin: 'ge', sv: 'styck' }] },
      ],
    },
    {
      id: 'word-list-status',
      titleSv: 'Ordlista och status',
      descriptionSv: 'Ord för ordlistan, dagens repetition och status på kort.',
      unlocksUiKeys: ['nav.progress', 'status.due', 'status.language', 'status.learnedCards', 'status.mastered', 'section.data'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-progress', sv: 'ordlista / lista med ord', hanzi: '词表', pinyin: 'cíbiǎo', uiKey: 'nav.progress', components: [{ hanzi: '词', pinyin: 'cí', sv: 'ord' }, { hanzi: '表', pinyin: 'biǎo', sv: 'lista / tabell' }] },
        { id: 'ui-number-char', sv: 'tal / antal', hanzi: '数', pinyin: 'shù', notesSv: 'Första tecknet i 数据.' },
        { id: 'ui-data-evidence-char', sv: 'grund / enligt', hanzi: '据', pinyin: 'jù', notesSv: 'Andra tecknet i 数据.' },
        { id: 'ui-data', sv: 'data', hanzi: '数据', pinyin: 'shùjù', uiKey: 'section.data', components: [{ hanzi: '数', pinyin: 'shù', sv: 'tal / antal' }, { hanzi: '据', pinyin: 'jù', sv: 'grund / enligt' }] },
        { id: 'ui-now-char', sv: 'nuvarande', hanzi: '今', pinyin: 'jīn', notesSv: 'Första tecknet i 今天.' },
        { id: 'ui-today', sv: 'idag', hanzi: '今天', pinyin: 'jīntiān', components: [{ hanzi: '今', pinyin: 'jīn', sv: 'nuvarande' }, { hanzi: '天', pinyin: 'tiān', sv: 'dag / himmel' }] },
        { id: 'ui-language-char', sv: 'språk', hanzi: '语', pinyin: 'yǔ', notesSv: 'Första tecknet i 语言.' },
        { id: 'ui-language', sv: 'språk', hanzi: '语言', pinyin: 'yǔyán', uiKey: 'status.language', components: [{ hanzi: '语', pinyin: 'yǔ', sv: 'språk' }, { hanzi: '言', pinyin: 'yán', sv: 'tal / ord' }] },
        { id: 'ui-need-char', sv: 'behöva / ska', hanzi: '要', pinyin: 'yào', notesSv: 'Första tecknet i 要复习.' },
        { id: 'ui-due', sv: 'att repetera', hanzi: '要复习', pinyin: 'yào fùxí', uiKey: 'status.due', components: [{ hanzi: '要', pinyin: 'yào', sv: 'behöva / ska' }, { hanzi: '复习', pinyin: 'fùxí', sv: 'repetera' }] },
        { id: 'ui-already-char', sv: 'redan', hanzi: '已', pinyin: 'yǐ', notesSv: 'Första tecknet i 已学: redan.' },
        {
          id: 'ui-learned-cards',
          sv: 'redan studerat / avklarat',
          hanzi: '已学',
          pinyin: 'yǐxué',
          uiKey: 'status.learnedCards',
          notesSv: 'I UI:t betyder statusen ”lärda kort”, men ordet 已学 säger bara redan studerat/avklarat. Kort står inte i kinesiskan.',
          components: [{ hanzi: '已', pinyin: 'yǐ', sv: 'redan' }, { hanzi: '学', pinyin: 'xué', sv: 'lära sig / studera' }],
        },
        { id: 'ui-mastered', sv: 'sitter / bekant', hanzi: '熟', pinyin: 'shú', uiKey: 'status.mastered', notesSv: 'Används här för ord som sitter: de känns bekanta och säkra.' },
      ],
    },
    {
      id: 'correct-streak',
      titleSv: 'Rätt i rad',
      descriptionSv: 'Bygg frasen som visar hur många gånger du har svarat rätt i följd.',
      unlocksUiKeys: ['status.correctStreak'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-consecutive', sv: 'i följd / sammanhängande', hanzi: '连续', pinyin: 'liánxù', components: [{ hanzi: '续', pinyin: 'xù', sv: 'fortsätta' }] },
        { id: 'ui-times', sv: 'gång / antal tillfällen', hanzi: '次', pinyin: 'cì' },
        {
          id: 'ui-correct-streak',
          sv: 'tre rätt i rad',
          hanzi: '连续答对 3 次',
          pinyin: 'liánxù dáduì sān cì',
          uiKey: 'status.correctStreak',
          notesSv: 'Siffran ändras i gränssnittet. 答对 betyder svara rätt och 次 räknar antal tillfällen.',
          components: [
            { hanzi: '连续', pinyin: 'liánxù', sv: 'i följd' },
            { hanzi: '答', pinyin: 'dá', sv: 'svara' },
            { hanzi: '对', pinyin: 'duì', sv: 'rätt' },
            { hanzi: '次', pinyin: 'cì', sv: 'gång / tillfälle' },
          ],
        },
      ],
    },
    {
      id: 'meaning-hanzi-pinyin',
      titleSv: 'Betydelse, tecken och pinyin',
      descriptionSv: 'Ord för de tre färdigheter som visas för varje kort i ordlistan.',
      unlocksUiKeys: ['term.meaning', 'term.hanzi', 'term.pinyin'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-meaning-char', sv: 'mening / betydelse', hanzi: '意', pinyin: 'yì', notesSv: 'Första tecknet i 意思: betydelse.' },
        { id: 'ui-meaning', sv: 'betydelse / mening', hanzi: '意思', pinyin: 'yìsi', uiKey: 'term.meaning', components: [{ hanzi: '意', pinyin: 'yì', sv: 'mening / betydelse' }] },
        { id: 'ui-written-character', sv: 'skrivtecken', hanzi: '字', pinyin: 'zì' },
        { id: 'ui-hanzi', sv: 'kinesiskt tecken / kinesiska tecken', hanzi: '汉字', pinyin: 'hànzì', uiKey: 'term.hanzi', components: [{ hanzi: '汉', pinyin: 'hàn', sv: 'kinesiska' }, { hanzi: '字', pinyin: 'zì', sv: 'skrivtecken' }] },
        { id: 'ui-spell-char', sv: 'sätta samman / stava', hanzi: '拼', pinyin: 'pīn', notesSv: 'Första tecknet i 拼音: pinyin.' },
        { id: 'ui-sound-char', sv: 'ljud', hanzi: '音', pinyin: 'yīn', notesSv: 'Andra tecknet i 拼音: pinyin.' },
        { id: 'ui-pinyin', sv: 'pinyin / kinesisk ljudskrift', hanzi: '拼音', pinyin: 'pīnyīn', uiKey: 'term.pinyin', components: [{ hanzi: '拼', pinyin: 'pīn', sv: 'sätta samman / stava' }, { hanzi: '音', pinyin: 'yīn', sv: 'ljud' }] },
      ],
    },
    {
      id: 'questions-multiple-choice',
      titleSv: 'Frågor och flerval',
      descriptionSv: 'Förstå instruktionerna på frågekorten och ordet för flervalsfråga.',
      unlocksUiKeys: ['exercise.multipleChoice', 'prompt.whatMeans', 'prompt.whichMeans'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-what-first-char', sv: 'vad', hanzi: '什', pinyin: 'shén', notesSv: 'Första tecknet i 什么: vad.' },
        { id: 'ui-what-particle', sv: 'frågedel', hanzi: '么', pinyin: 'me', notesSv: 'Andra tecknet i 什么: vad.' },
        { id: 'ui-what', sv: 'vad', hanzi: '什么', pinyin: 'shénme', components: [{ hanzi: '什', pinyin: 'shén', sv: 'vad' }, { hanzi: '么', pinyin: 'me', sv: 'frågedel' }] },
        {
          id: 'ui-what-means',
          sv: 'vad betyder det?',
          hanzi: '是什么意思？',
          pinyin: 'shì shénme yìsi?',
          uiKey: 'prompt.whatMeans',
          notesSv: 'På frågekorten sätts det aktuella ordet före frasen, till exempel 习 是什么意思？',
          components: [{ hanzi: '什么', pinyin: 'shénme', sv: 'vad' }, { hanzi: '意思', pinyin: 'yìsi', sv: 'betydelse / mening' }],
        },
        { id: 'ui-which', sv: 'vilken / vilket', hanzi: '哪个', pinyin: 'nǎge', components: [{ hanzi: '个', pinyin: 'ge', sv: 'styck / måttsord' }] },
        { id: 'ui-possessive-particle', sv: 'bestämningspartikel', hanzi: '的', pinyin: 'de', notesSv: 'Binder ihop en bestämning med det som beskrivs, här i frågan 哪个是…的意思？' },
        {
          id: 'ui-which-means',
          sv: 'vilket betyder det?',
          hanzi: '哪个是它的意思？',
          pinyin: 'nǎge shì tā de yìsi?',
          uiKey: 'prompt.whichMeans',
          notesSv: 'På frågekorten ersätts 它 med den svenska betydelsen, till exempel 哪个是“öva”的意思？',
          components: [{ hanzi: '哪个', pinyin: 'nǎge', sv: 'vilken / vilket' }, { hanzi: '的', pinyin: 'de', sv: 'bestämningspartikel' }, { hanzi: '意思', pinyin: 'yìsi', sv: 'betydelse / mening' }],
        },
        { id: 'ui-choose-char', sv: 'välja', hanzi: '选', pinyin: 'xuǎn', notesSv: 'Första tecknet i 选择: välja.' },
        { id: 'ui-choose', sv: 'välja / val', hanzi: '选择', pinyin: 'xuǎnzé', components: [{ hanzi: '选', pinyin: 'xuǎn', sv: 'välja' }] },
        { id: 'ui-question-task', sv: 'fråga / uppgift', hanzi: '题', pinyin: 'tí' },
        { id: 'ui-multiple-choice', sv: 'flervalsfråga', hanzi: '选择题', pinyin: 'xuǎnzétí', uiKey: 'exercise.multipleChoice', components: [{ hanzi: '选择', pinyin: 'xuǎnzé', sv: 'välja / val' }, { hanzi: '题', pinyin: 'tí', sv: 'fråga / uppgift' }] },
      ],
    },
    {
      id: 'search-card-status',
      titleSv: 'Sökning och kortstatus',
      descriptionSv: 'Sök i ordlistan och förstå hur starka eller nya kort är.',
      unlocksUiKeys: ['action.searchWordList', 'status.strong', 'status.newWeak', 'status.now'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-search-char', sv: 'söka / leta', hanzi: '搜', pinyin: 'sōu', notesSv: 'Första tecknet i 搜索: söka.' },
        { id: 'ui-search', sv: 'söka', hanzi: '搜索', pinyin: 'sōusuǒ', components: [{ hanzi: '搜', pinyin: 'sōu', sv: 'söka / leta' }] },
        { id: 'ui-search-word-list', sv: 'sök i ordlistan', hanzi: '搜索词表', pinyin: 'sōusuǒ cíbiǎo', uiKey: 'action.searchWordList', components: [{ hanzi: '搜索', pinyin: 'sōusuǒ', sv: 'söka' }, { hanzi: '词表', pinyin: 'cíbiǎo', sv: 'ordlista' }] },
        { id: 'ui-strong', sv: 'stark', hanzi: '强', pinyin: 'qiáng', uiKey: 'status.strong' },
        { id: 'ui-new-char', sv: 'ny', hanzi: '新', pinyin: 'xīn' },
        { id: 'ui-weak-char', sv: 'svag', hanzi: '弱', pinyin: 'ruò' },
        { id: 'ui-new-weak', sv: 'ny / svag', hanzi: '新 / 弱', pinyin: 'xīn / ruò', uiKey: 'status.newWeak', components: [{ hanzi: '新', pinyin: 'xīn', sv: 'ny' }, { hanzi: '弱', pinyin: 'ruò', sv: 'svag' }] },
        { id: 'ui-present-char', sv: 'nuvarande / synlig', hanzi: '现', pinyin: 'xiàn', notesSv: 'Första tecknet i 现在: nu.' },
        { id: 'ui-now', sv: 'nu', hanzi: '现在', pinyin: 'xiànzài', uiKey: 'status.now', components: [{ hanzi: '现', pinyin: 'xiàn', sv: 'nuvarande / synlig' }] },
      ],
    },
    {
      id: 'backup-data-actions',
      titleSv: 'Backup och datahantering',
      descriptionSv: 'Export, import, avbryt och nollställ i inställningarna.',
      unlocksUiKeys: ['action.export', 'action.import', 'action.reset', 'action.cancel'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-keep-char', sv: 'skydda / behålla', hanzi: '保', pinyin: 'bǎo', notesSv: 'Första tecknet i 保存.' },
        { id: 'ui-save', sv: 'spara', hanzi: '保存', pinyin: 'bǎocún', components: [{ hanzi: '保', pinyin: 'bǎo', sv: 'skydda / behålla' }, { hanzi: '存', pinyin: 'cún', sv: 'spara / lagra' }] },
        { id: 'ui-take-char', sv: 'ta', hanzi: '取', pinyin: 'qǔ', notesSv: 'Första tecknet i 取消.' },
        { id: 'ui-cancel', sv: 'avbryt', hanzi: '取消', pinyin: 'qǔxiāo', uiKey: 'action.cancel', components: [{ hanzi: '取', pinyin: 'qǔ', sv: 'ta' }, { hanzi: '消', pinyin: 'xiāo', sv: 'försvinna / ta bort' }] },
        { id: 'ui-prepare-char', sv: 'förbereda / utrusta', hanzi: '备', pinyin: 'bèi', notesSv: 'Används i 备份: backup. I 准备 betyder det förberedelse.' },
        { id: 'ui-portion-char', sv: 'del / exemplar', hanzi: '份', pinyin: 'fèn', notesSv: 'Vanligt tecken. Används i 备份 och till exempel 三份 (tre exemplar) och 月份 (månad).' },
        { id: 'ui-backup', sv: 'backup', hanzi: '备份', pinyin: 'bèifèn', components: [{ hanzi: '备', pinyin: 'bèi', sv: 'förbereda / utrusta' }, { hanzi: '份', pinyin: 'fèn', sv: 'del / exemplar' }] },
        { id: 'ui-out-char', sv: 'ut', hanzi: '出', pinyin: 'chū', notesSv: 'Används i 导出: exportera/föra ut.' },
        { id: 'ui-export', sv: 'exportera backup', hanzi: '导出备份', pinyin: 'dǎochū bèifèn', uiKey: 'action.export', components: [{ hanzi: '出', pinyin: 'chū', sv: 'ut' }, { hanzi: '备份', pinyin: 'bèifèn', sv: 'backup' }] },
        { id: 'ui-in-char', sv: 'in', hanzi: '入', pinyin: 'rù', notesSv: 'Används i 导入: importera/föra in.' },
        { id: 'ui-import', sv: 'importera backup', hanzi: '导入备份', pinyin: 'dǎorù bèifèn', uiKey: 'action.import', components: [{ hanzi: '入', pinyin: 'rù', sv: 'in' }, { hanzi: '备份', pinyin: 'bèifèn', sv: 'backup' }] },
        { id: 'ui-reset', sv: 'nollställ', hanzi: '重置', pinyin: 'chóngzhì', uiKey: 'action.reset', components: [{ hanzi: '置', pinyin: 'zhì', sv: 'sätta / placera' }] },
      ],
    },
    {
      id: 'settings-version-build',
      revision: 2,
      titleSv: 'Teknisk info: uppdatering, version och build',
      descriptionSv: 'Uppdatera, version, builddatum och asset-version i inställningarna.',
      unlocksUiKeys: ['action.update', 'term.version', 'term.build', 'term.buildDate', 'term.assetVersion'],
      uiKeyRevisions: { 'action.update': 2 },
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-update-first-char', addedInRevision: 2, sv: 'ändra / mer', hanzi: '更', pinyin: 'gēng', notesSv: 'Första tecknet i 更新: uppdatera.' },
        { id: 'ui-update-second-char', addedInRevision: 2, sv: 'ny', hanzi: '新', pinyin: 'xīn', notesSv: 'Andra tecknet i 更新: uppdatera.' },
        { id: 'ui-update', addedInRevision: 2, sv: 'uppdatera / förnya', hanzi: '更新', pinyin: 'gēngxīn', uiKey: 'action.update', components: [{ hanzi: '更', pinyin: 'gēng', sv: 'ändra / mer' }, { hanzi: '新', pinyin: 'xīn', sv: 'ny' }] },
        { id: 'ui-version-char', sv: 'version / upplaga', hanzi: '版', pinyin: 'bǎn', notesSv: 'Första tecknet i 版本.' },
        { id: 'ui-version', sv: 'version', hanzi: '版本', pinyin: 'bǎnběn', uiKey: 'term.version', components: [{ hanzi: '版', pinyin: 'bǎn', sv: 'version / upplaga' }] },
        { id: 'ui-build-char', sv: 'bygga / konstruera', hanzi: '构', pinyin: 'gòu', notesSv: 'Första tecknet i 构建.' },
        { id: 'ui-build', sv: 'build / bygga', hanzi: '构建', pinyin: 'gòujiàn', uiKey: 'term.build', components: [{ hanzi: '构', pinyin: 'gòu', sv: 'bygga / konstruera' }] },
        { id: 'ui-day-char', sv: 'dag / sol', hanzi: '日', pinyin: 'rì', notesSv: 'Vanligt tecken för dag. Här används det i 日期: datum.' },
        { id: 'ui-date', sv: 'datum', hanzi: '日期', pinyin: 'rìqī', components: [{ hanzi: '日', pinyin: 'rì', sv: 'dag / sol' }] },
        { id: 'ui-build-date', sv: 'byggdatum', hanzi: '构建日期', pinyin: 'gòujiàn rìqī', uiKey: 'term.buildDate', components: [{ hanzi: '构建', pinyin: 'gòujiàn', sv: 'build' }, { hanzi: '日期', pinyin: 'rìqī', sv: 'datum' }] },
        { id: 'ui-resource-char', sv: 'resurs / tillgång', hanzi: '资', pinyin: 'zī', notesSv: 'Första tecknet i 资源.' },
        { id: 'ui-resource', sv: 'resurs / asset', hanzi: '资源', pinyin: 'zīyuán', components: [{ hanzi: '资', pinyin: 'zī', sv: 'resurs / tillgång' }] },
        { id: 'ui-asset-version', sv: 'asset-version', hanzi: '资源版本', pinyin: 'zīyuán bǎnběn', uiKey: 'term.assetVersion', components: [{ hanzi: '资源', pinyin: 'zīyuán', sv: 'resurs / asset' }, { hanzi: '版本', pinyin: 'bǎnběn', sv: 'version' }] },
      ],
    },
    {
      id: 'settings-license-contact',
      revision: 2,
      titleSv: 'Teknisk info: källkod, licens och kontakt',
      descriptionSv: 'Källkod, licens, kontakt och rubriken Licens & kontakt.',
      unlocksUiKeys: ['section.licenseContact', 'term.sourceCode', 'term.license', 'term.contact'],
      uiKeyRevisions: { 'term.sourceCode': 2 },
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-source-char', addedInRevision: 2, sv: 'källa / ursprung', hanzi: '源', pinyin: 'yuán', notesSv: 'Första tecknet i 源代码: källkod.' },
        { id: 'ui-code-char', addedInRevision: 2, sv: 'kod / nummer', hanzi: '码', pinyin: 'mǎ', notesSv: 'Används i 代码: kod.' },
        { id: 'ui-code', addedInRevision: 2, sv: 'kod', hanzi: '代码', pinyin: 'dàimǎ', components: [{ hanzi: '码', pinyin: 'mǎ', sv: 'kod / nummer' }] },
        { id: 'ui-source-code', addedInRevision: 2, sv: 'källkod', hanzi: '源代码', pinyin: 'yuán dàimǎ', uiKey: 'term.sourceCode', components: [{ hanzi: '源', pinyin: 'yuán', sv: 'källa / ursprung' }, { hanzi: '代码', pinyin: 'dàimǎ', sv: 'kod' }] },
        { id: 'ui-permit-char', sv: 'kan / får', hanzi: '可', pinyin: 'kě', notesSv: 'Vanligt tecken för kan/får. Här används det i 许可.' },
        { id: 'ui-license', sv: 'licens / tillåtelse', hanzi: '许可', pinyin: 'xǔkě', uiKey: 'term.license', components: [{ hanzi: '可', pinyin: 'kě', sv: 'kan / får' }] },
        { id: 'ui-contact-char', sv: 'koppla / förena', hanzi: '联', pinyin: 'lián', notesSv: 'Första tecknet i 联系.' },
        { id: 'ui-contact', sv: 'kontakt', hanzi: '联系', pinyin: 'liánxì', uiKey: 'term.contact', components: [{ hanzi: '联', pinyin: 'lián', sv: 'koppla / förena' }] },
        { id: 'ui-and-char', sv: 'och / med', hanzi: '与', pinyin: 'yǔ', notesSv: 'Används här som och mellan licens och kontakt.' },
        { id: 'ui-license-contact', sv: 'licens & kontakt', hanzi: '许可与联系', pinyin: 'xǔkě yǔ liánxì', uiKey: 'section.licenseContact', components: [{ hanzi: '许可', pinyin: 'xǔkě', sv: 'licens' }, { hanzi: '与', pinyin: 'yǔ', sv: 'och' }, { hanzi: '联系', pinyin: 'liánxì', sv: 'kontakt' }] },
      ],
    },
  ],
};
