export const appUiBasics = {
  id: 'app-ui-basics',
  titleSv: 'App UI: grunder',
  titleZh: '应用界面基础',
  pinyin: 'yìngyòng jièmiàn jīchǔ',
  descriptionSv: 'Börja här. Du lär dig de ord som appen själv använder, och gränssnittet blir gradvis kinesiskt.',
  order: 0,
  lessons: [
    {
      id: 'first-characters',
      titleSv: 'Första tecken',
      descriptionSv: 'En mjuk start med korta en-teckenord innan längre knapptexter.',
      unlocksUiKeys: ['term.word', 'feedback.correct', 'feedback.wrong'],
      unlocksExerciseTypes: ['type-pinyin'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-chinese', sv: 'kinesiska / Kina', hanzi: '中', pinyin: 'zhōng', notesSv: 'Syns i appikonen. I ord som 中文 betyder det kinesiska språket.' },
        { id: 'ui-text', sv: 'text / språk', hanzi: '文', pinyin: 'wén', notesSv: 'Används i 中文: kinesiska språket.' },
        { id: 'ui-word', sv: 'ord', hanzi: '词', pinyin: 'cí', uiKey: 'term.word' },
        { id: 'ui-correct', sv: 'rätt', hanzi: '对', pinyin: 'duì', uiKey: 'feedback.correct' },
        { id: 'ui-wrong', sv: 'fel', hanzi: '错', pinyin: 'cuò', uiKey: 'feedback.wrong' },
      ],
    },
    {
      id: 'start-button',
      titleSv: 'Startknappen',
      descriptionSv: 'Bygg upp 开始 från två enklare tecken.',
      unlocksUiKeys: ['action.start'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-open', sv: 'öppna / starta', hanzi: '开', pinyin: 'kāi', notesSv: 'Första tecknet i 开始.' },
        { id: 'ui-begin-char', sv: 'börja', hanzi: '始', pinyin: 'shǐ', notesSv: 'Andra tecknet i 开始.' },
        {
          id: 'ui-start',
          sv: 'starta / börja',
          hanzi: '开始',
          pinyin: 'kāishǐ',
          uiKey: 'action.start',
          notesSv: 'Vanligt för Start eller Börja.',
          components: [
            { hanzi: '开', pinyin: 'kāi', sv: 'öppna / starta' },
            { hanzi: '始', pinyin: 'shǐ', sv: 'börja' },
          ],
        },
      ],
    },
    {
      id: 'home-button',
      titleSv: 'Hem och startsida',
      descriptionSv: 'Först tecknen, sedan hela ordet 首页.',
      unlocksUiKeys: ['nav.home'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-first-page', sv: 'första / huvud-', hanzi: '首', pinyin: 'shǒu', notesSv: 'Första tecknet i 首页.' },
        { id: 'ui-page', sv: 'sida', hanzi: '页', pinyin: 'yè', notesSv: 'Andra tecknet i 首页.' },
        {
          id: 'ui-home',
          sv: 'hem / startsida',
          hanzi: '首页',
          pinyin: 'shǒuyè',
          uiKey: 'nav.home',
          notesSv: 'Betyder ungefär första sida/startsida.',
          components: [
            { hanzi: '首', pinyin: 'shǒu', sv: 'första / huvud-' },
            { hanzi: '页', pinyin: 'yè', sv: 'sida' },
          ],
        },
      ],
    },
    {
      id: 'back-button',
      titleSv: 'Tillbaka',
      descriptionSv: 'Först 回, sedan knappordet 返回.',
      unlocksUiKeys: ['action.back'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-return-char', sv: 'återvända / tillbaka', hanzi: '回', pinyin: 'huí', notesSv: 'Används i flera ord som handlar om att gå tillbaka.' },
        {
          id: 'ui-back',
          sv: 'tillbaka',
          hanzi: '返回',
          pinyin: 'fǎnhuí',
          uiKey: 'action.back',
          notesSv: 'Vanlig knapp för att gå tillbaka.',
          components: [
            { hanzi: '返', pinyin: 'fǎn', sv: 'återvända' },
            { hanzi: '回', pinyin: 'huí', sv: 'tillbaka / åter' },
          ],
        },
      ],
    },
    {
      id: 'settings-button',
      titleSv: 'Inställningar',
      descriptionSv: 'Först 设 och 置, sedan 设置.',
      unlocksUiKeys: ['settings.title'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-set-up-char', sv: 'ställa in / ordna', hanzi: '设', pinyin: 'shè', notesSv: 'Första tecknet i 设置.' },
        { id: 'ui-place-char', sv: 'placera / sätta', hanzi: '置', pinyin: 'zhì', notesSv: 'Andra tecknet i 设置.' },
        {
          id: 'ui-settings',
          sv: 'inställningar',
          hanzi: '设置',
          pinyin: 'shèzhì',
          uiKey: 'settings.title',
          notesSv: 'Mycket vanlig menytext i appar.',
          components: [
            { hanzi: '设', pinyin: 'shè', sv: 'ställa in' },
            { hanzi: '置', pinyin: 'zhì', sv: 'placera / sätta' },
          ],
        },
      ],
    },
    {
      id: 'app-hanhan-name',
      titleSv: 'Appens namn: 汉汉',
      descriptionSv: 'Tecknet 汉 för kinesiska språket, och hur det blir appens namn i reduplikation.',
      unlocksUiKeys: ['app.title', 'nav.about'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-han-char', sv: 'kinesiska (språk)', hanzi: '汉', pinyin: 'hàn', notesSv: 'En förkortning för kinesiska språket, som i 汉语.' },
        {
          id: 'ui-hanhan-name',
          sv: 'appens namn',
          hanzi: '汉汉',
          pinyin: 'hàn hàn',
          uiKey: 'app.title',
          notesSv: 'Appens namn: Hàn betyder kinesiska språket. Fördubblat som en vänlig smekform, på samma sätt som andra appar.',
          components: [
            { hanzi: '汉', pinyin: 'hàn', sv: 'kinesiska språket' },
          ],
        },
        { id: 'ui-about-char', sv: 'stänga / relatera', hanzi: '关', pinyin: 'guān', notesSv: 'Första tecknet i 关于.' },
        { id: 'ui-about-word', sv: 'om / angående', hanzi: '关于', pinyin: 'guānyú', components: [{ hanzi: '关', pinyin: 'guān', sv: 'relatera' }] },
        {
          id: 'ui-about-hanhan',
          sv: 'Om HànHàn',
          hanzi: '关于汉汉',
          pinyin: 'guānyú hàn hàn',
          uiKey: 'nav.about',
          notesSv: 'Vanlig rubrik för en Om-sida: 关于 betyder om eller angående.',
          components: [
            { hanzi: '关于', pinyin: 'guānyú', sv: 'om / angående' },
            { hanzi: '汉汉', pinyin: 'hàn hàn', sv: 'HànHàn' },
          ],
        },
      ],
    },
    {
      id: 'review-actions',
      titleSv: 'Repetera',
      descriptionSv: 'Bara repetitionsknappen, så lektionen blir kortare.',
      unlocksUiKeys: ['action.review', 'review.title'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-practice-study-char', sv: 'öva / studera', hanzi: '习', pinyin: 'xí', notesSv: 'Andra tecknet i 复习.' },
        { id: 'ui-review', sv: 'repetera', hanzi: '复习', pinyin: 'fùxí', uiKey: 'action.review', components: [{ hanzi: '习', pinyin: 'xí', sv: 'öva / studera' }] },
        { id: 'ui-review-title', sv: 'repetition', hanzi: '复习', pinyin: 'fùxí', uiKey: 'review.title', components: [{ hanzi: '习', pinyin: 'xí', sv: 'öva / studera' }] },
      ],
    },
    {
      id: 'learn-actions',
      titleSv: 'Lära och öva',
      descriptionSv: 'Lära och öva, med ett gemensamt tecken.',
      unlocksUiKeys: ['action.learn', 'action.practice'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-study-char', sv: 'lära / studera', hanzi: '学', pinyin: 'xué', notesSv: 'Första tecknet i 学习.' },
        { id: 'ui-learn', sv: 'lära sig / studera', hanzi: '学习', pinyin: 'xuéxí', uiKey: 'action.learn', components: [{ hanzi: '学', pinyin: 'xué', sv: 'lära / studera' }, { hanzi: '习', pinyin: 'xí', sv: 'öva' }] },
        { id: 'ui-train-char', sv: 'träna', hanzi: '练', pinyin: 'liàn', notesSv: 'Första tecknet i 练习.' },
        { id: 'ui-practice', sv: 'öva', hanzi: '练习', pinyin: 'liànxí', uiKey: 'action.practice', components: [{ hanzi: '练', pinyin: 'liàn', sv: 'träna' }, { hanzi: '习', pinyin: 'xí', sv: 'öva' }] },
      ],
    },
    {
      id: 'continue-lesson',
      titleSv: 'Fortsätt och lektion',
      descriptionSv: 'Två vanliga ord i lektionsflödet.',
      unlocksUiKeys: ['action.continue', 'lesson.title', 'lesson.complete', 'status.inProgress', 'status.incomplete'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-continue-char', sv: 'fortsätta', hanzi: '续', pinyin: 'xù', notesSv: 'Ett tecken i 继续.' },
        { id: 'ui-continue', sv: 'fortsätt', hanzi: '继续', pinyin: 'jìxù', uiKey: 'action.continue', components: [{ hanzi: '续', pinyin: 'xù', sv: 'fortsätta' }] },
        { id: 'ui-class-char', sv: 'lektion', hanzi: '课', pinyin: 'kè', notesSv: 'Första tecknet i 课程.' },
        { id: 'ui-lesson', sv: 'lektion / kurs', hanzi: '课程', pinyin: 'kèchéng', uiKey: 'lesson.title', components: [{ hanzi: '课', pinyin: 'kè', sv: 'lektion' }, { hanzi: '程', pinyin: 'chéng', sv: 'kurs / process' }] },
        { id: 'ui-complete-char1', sv: 'färdig / komplett', hanzi: '完', pinyin: 'wán', notesSv: 'Första tecknet i 完成.' },
        { id: 'ui-complete-char2', sv: 'bli / åstadkomma', hanzi: '成', pinyin: 'chéng', notesSv: 'Andra tecknet i 完成.' },
        { id: 'ui-complete', sv: 'klar / slutförd', hanzi: '完成', pinyin: 'wánchéng', uiKey: 'lesson.complete', components: [{ hanzi: '完', pinyin: 'wán', sv: 'färdig / komplett' }, { hanzi: '成', pinyin: 'chéng', sv: 'bli / åstadkomma' }] },
        { id: 'ui-progressing', sv: 'pågående', hanzi: '进行中', pinyin: 'jìnxíng zhōng', uiKey: 'status.inProgress', components: [{ hanzi: '中', pinyin: 'zhōng', sv: 'i / mitten' }] },
        { id: 'ui-not-yet-char', sv: 'inte ännu', hanzi: '未', pinyin: 'wèi', notesSv: 'Första tecknet i 未完成.' },
        { id: 'ui-incomplete', sv: 'ej klar', hanzi: '未完成', pinyin: 'wèi wánchéng', uiKey: 'status.incomplete', components: [{ hanzi: '未', pinyin: 'wèi', sv: 'inte ännu' }, { hanzi: '完成', pinyin: 'wánchéng', sv: 'klar / slutförd' }] },
      ],
    },
    {
      id: 'answers-feedback',
      titleSv: 'Svar och feedback',
      descriptionSv: 'Svar, visa svar och nästa.',
      unlocksUiKeys: ['term.answer', 'action.next', 'action.showAnswer'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-answer-char', sv: 'svara', hanzi: '答', pinyin: 'dá', notesSv: 'Första tecknet i 答案.' },
        { id: 'ui-answer', sv: 'svar', hanzi: '答案', pinyin: 'dá’àn', uiKey: 'term.answer', components: [{ hanzi: '答', pinyin: 'dá', sv: 'svara' }, { hanzi: '案', pinyin: 'àn', sv: 'förslag / fall' }] },
        { id: 'ui-show-char1', sv: 'synas / framträda', hanzi: '显', pinyin: 'xiǎn', notesSv: 'Första tecknet i 显示.' },
        { id: 'ui-show-char2', sv: 'visa / indikera', hanzi: '示', pinyin: 'shì', notesSv: 'Andra tecknet i 显示.' },
        { id: 'ui-show-word', sv: 'visa', hanzi: '显示', pinyin: 'xiǎnshì', notesSv: 'Första delen av 显示答案. Används ofta i appar för att visa något.', components: [{ hanzi: '显', pinyin: 'xiǎn', sv: 'synas / framträda' }, { hanzi: '示', pinyin: 'shì', sv: 'visa / indikera' }] },
        { id: 'ui-show-answer', sv: 'visa svar', hanzi: '显示答案', pinyin: 'xiǎnshì dá’àn', uiKey: 'action.showAnswer', components: [{ hanzi: '显示', pinyin: 'xiǎnshì', sv: 'visa' }, { hanzi: '答案', pinyin: 'dá’àn', sv: 'svar' }] },
        { id: 'ui-down-next-char', sv: 'nästa / ned', hanzi: '下', pinyin: 'xià', notesSv: 'Första tecknet i 下一个.' },
        { id: 'ui-one-char', sv: 'ett', hanzi: '一', pinyin: 'yī', notesSv: 'Andra tecknet i 下一个. Grundläggande räkneord.' },
        { id: 'ui-measure-char', sv: 'styck (måttsord)', hanzi: '个', pinyin: 'ge', notesSv: 'Tredje tecknet i 下一个. Ett vanligt måttsord.' },
        { id: 'ui-next', sv: 'nästa', hanzi: '下一个', pinyin: 'xià yí ge', uiKey: 'action.next', components: [{ hanzi: '下', pinyin: 'xià', sv: 'nästa / ned' }, { hanzi: '一', pinyin: 'yī', sv: 'ett' }, { hanzi: '个', pinyin: 'ge', sv: 'styck' }] },
      ],
    },
    {
      id: 'data-progress',
      titleSv: 'Ordlista och data',
      descriptionSv: 'Ord för dagens repetition, språk och backup.',
      unlocksUiKeys: ['nav.progress', 'status.due', 'status.language', 'status.learnedCards', 'status.mastered', 'section.data', 'action.export', 'action.import', 'action.reset', 'action.cancel'],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'ui-progress', sv: 'ordlista / lista med ord', hanzi: '词表', pinyin: 'cíbiǎo', uiKey: 'nav.progress', components: [{ hanzi: '词', pinyin: 'cí', sv: 'ord' }, { hanzi: '表', pinyin: 'biǎo', sv: 'lista / tabell' }] },
        { id: 'ui-number-char', sv: 'tal / antal', hanzi: '数', pinyin: 'shù', notesSv: 'Första tecknet i 数据.' },
        { id: 'ui-data-evidence-char', sv: 'grund / enligt', hanzi: '据', pinyin: 'jù', notesSv: 'Andra tecknet i 数据.' },
        { id: 'ui-data', sv: 'data', hanzi: '数据', pinyin: 'shùjù', uiKey: 'section.data', components: [{ hanzi: '数', pinyin: 'shù', sv: 'tal / antal' }, { hanzi: '据', pinyin: 'jù', sv: 'grund / enligt' }] },
        { id: 'ui-now-char', sv: 'nuvarande', hanzi: '今', pinyin: 'jīn', notesSv: 'Första tecknet i 今天.' },
        { id: 'ui-today', sv: 'idag', hanzi: '今天', pinyin: 'jīntiān', components: [{ hanzi: '今', pinyin: 'jīn', sv: 'nuvarande' }, { hanzi: '天', pinyin: 'tiān', sv: 'dag / himmel' }] },
        { id: 'ui-language-char', sv: 'språk', hanzi: '语', pinyin: 'yǔ', notesSv: 'Första tecknet i 语言.' },
        { id: 'ui-language', sv: 'språk', hanzi: '语言', pinyin: 'yǔyán', uiKey: 'status.language', components: [{ hanzi: '语', pinyin: 'yǔ', sv: 'språk' }, { hanzi: '言', pinyin: 'yán', sv: 'tal / ord' }] },
        { id: 'ui-need-char', sv: 'behöva / ska', hanzi: '要', pinyin: 'yào', notesSv: 'Första tecknet i 要复习.' },
        { id: 'ui-due', sv: 'att repetera', hanzi: '要复习', pinyin: 'yào fùxí', uiKey: 'status.due', components: [{ hanzi: '要', pinyin: 'yào', sv: 'behöva / ska' }, { hanzi: '复习', pinyin: 'fùxí', sv: 'repetera' }] },
        { id: 'ui-already-char', sv: 'redan', hanzi: '已', pinyin: 'yǐ', notesSv: 'Första tecknet i 已学: redan lärt.' },
        { id: 'ui-learned-cards', sv: 'lärda kort', hanzi: '已学', pinyin: 'yǐxué', uiKey: 'status.learnedCards', components: [{ hanzi: '已', pinyin: 'yǐ', sv: 'redan' }, { hanzi: '学', pinyin: 'xué', sv: 'lära sig' }] },
        { id: 'ui-mastered', sv: 'sitter / bekant', hanzi: '熟', pinyin: 'shú', uiKey: 'status.mastered', notesSv: 'Används här för ord som sitter: de känns bekanta och säkra.' },
        { id: 'ui-keep-char', sv: 'skydda / behålla', hanzi: '保', pinyin: 'bǎo', notesSv: 'Första tecknet i 保存.' },
        { id: 'ui-save', sv: 'spara', hanzi: '保存', pinyin: 'bǎocún', components: [{ hanzi: '保', pinyin: 'bǎo', sv: 'skydda / behålla' }, { hanzi: '存', pinyin: 'cún', sv: 'spara / lagra' }] },
        { id: 'ui-take-char', sv: 'ta', hanzi: '取', pinyin: 'qǔ', notesSv: 'Första tecknet i 取消.' },
        { id: 'ui-cancel', sv: 'avbryt', hanzi: '取消', pinyin: 'qǔxiāo', uiKey: 'action.cancel', components: [{ hanzi: '取', pinyin: 'qǔ', sv: 'ta' }, { hanzi: '消', pinyin: 'xiāo', sv: 'försvinna / ta bort' }] },
        { id: 'ui-out-char', sv: 'ut', hanzi: '出', pinyin: 'chū', notesSv: 'Används i 导出: exportera/föra ut.' },
        { id: 'ui-export', sv: 'exportera backup', hanzi: '导出备份', pinyin: 'dǎochū bèifèn', uiKey: 'action.export', components: [{ hanzi: '出', pinyin: 'chū', sv: 'ut' }, { hanzi: '备份', pinyin: 'bèifèn', sv: 'backup' }] },
        { id: 'ui-in-char', sv: 'in', hanzi: '入', pinyin: 'rù', notesSv: 'Används i 导入: importera/föra in.' },
        { id: 'ui-import', sv: 'importera backup', hanzi: '导入备份', pinyin: 'dǎorù bèifèn', uiKey: 'action.import', components: [{ hanzi: '入', pinyin: 'rù', sv: 'in' }, { hanzi: '备份', pinyin: 'bèifèn', sv: 'backup' }] },
        { id: 'ui-reset', sv: 'nollställ', hanzi: '重置', pinyin: 'chóngzhì', uiKey: 'action.reset', components: [{ hanzi: '置', pinyin: 'zhì', sv: 'sätta / placera' }] },
      ],
    },
  ],
};
