export const homeBasics = {
  id: 'home-basics',
  titleSv: 'Hemma: grunder',
  titleZh: '家庭基础',
  pinyin: 'jiātíng jīchǔ',
  descriptionSv: 'Ord och korta fraser för familj, barn och vardag hemma.',
  order: 1,
  lessons: [
    {
      id: 'family',
      titleSv: 'Familj',
      descriptionSv: 'De första familjeorden, med enkla tecken före hela ord.',
      unlocksUiKeys: [],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'home-mom-char', sv: 'mamma', hanzi: '妈', pinyin: 'mā', notesSv: 'Tecknet upprepas i 妈妈.' },
        { id: 'home-mom', sv: 'mamma', hanzi: '妈妈', pinyin: 'māma', notesSv: 'Vanligt familjeord.', components: [{ hanzi: '妈', pinyin: 'mā', sv: 'mamma' }] },
        { id: 'home-dad-char', sv: 'pappa', hanzi: '爸', pinyin: 'bà', notesSv: 'Tecknet upprepas i 爸爸.' },
        { id: 'home-dad', sv: 'pappa', hanzi: '爸爸', pinyin: 'bàba', components: [{ hanzi: '爸', pinyin: 'bà', sv: 'pappa' }] },
        { id: 'home-child-char', sv: 'barn / son', hanzi: '子', pinyin: 'zi', notesSv: 'Andra tecknet i 孩子.' },
        { id: 'home-child', sv: 'barn', hanzi: '孩子', pinyin: 'háizi', components: [{ hanzi: '子', pinyin: 'zi', sv: 'barn / son' }] },
        { id: 'home-old-char', sv: 'gammal / nära', hanzi: '老', pinyin: 'lǎo', notesSv: 'Första tecknet i 老婆.' },
        { id: 'home-wife', sv: 'fru / frun', hanzi: '老婆', pinyin: 'lǎopo', notesSv: 'Vardagligt ord för fru/hustru.', components: [{ hanzi: '老', pinyin: 'lǎo', sv: 'gammal / nära' }] },
        { id: 'home-family-home-char', sv: 'hem / familj', hanzi: '家', pinyin: 'jiā', notesSv: 'Första tecknet i 家人.' },
        { id: 'home-family', sv: 'familj', hanzi: '家人', pinyin: 'jiārén', components: [{ hanzi: '家', pinyin: 'jiā', sv: 'hem / familj' }] },
      ],
    },
    {
      id: 'daily-commands',
      titleSv: 'Korta vardagsfraser',
      descriptionSv: 'Sånt man ofta säger hemma till barn, med byggstenar först.',
      unlocksUiKeys: [],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'home-come-char', sv: 'komma', hanzi: '来', pinyin: 'lái', notesSv: 'Andra tecknet i 过来.' },
        { id: 'home-come-here', sv: 'kom hit', hanzi: '过来', pinyin: 'guòlái', components: [{ hanzi: '来', pinyin: 'lái', sv: 'komma' }] },
        { id: 'home-wait-char', sv: 'vänta', hanzi: '等', pinyin: 'děng', notesSv: 'Första tecknet i 等一下.' },
        { id: 'home-wait', sv: 'vänta lite', hanzi: '等一下', pinyin: 'děng yíxià', components: [{ hanzi: '等', pinyin: 'děng', sv: 'vänta' }] },
        { id: 'home-fast-char', sv: 'snabb', hanzi: '快', pinyin: 'kuài', notesSv: 'Första tecknet i 快点.' },
        { id: 'home-hurry', sv: 'skynda dig', hanzi: '快点', pinyin: 'kuài diǎn', components: [{ hanzi: '快', pinyin: 'kuài', sv: 'snabb' }] },
        { id: 'home-stop', sv: 'sluta / stopp', hanzi: '停', pinyin: 'tíng' },
        { id: 'home-sit-char', sv: 'sitta', hanzi: '坐', pinyin: 'zuò', notesSv: 'Första tecknet i 坐下.' },
        { id: 'home-sit', sv: 'sitt ner', hanzi: '坐下', pinyin: 'zuò xià', components: [{ hanzi: '坐', pinyin: 'zuò', sv: 'sitta' }] },
      ],
    },
    {
      id: 'eat-drink-sleep',
      titleSv: 'Äta, dricka, sova',
      descriptionSv: 'Mycket vanliga ord hemma, med byggstenar före hela fraser.',
      unlocksUiKeys: [],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'home-eat-char', sv: 'äta', hanzi: '吃', pinyin: 'chī', notesSv: 'Första tecknet i 吃饭.' },
        { id: 'home-rice-food', sv: 'ris / mat', hanzi: '饭', pinyin: 'fàn', notesSv: 'Andra tecknet i 吃饭; kan betyda ris eller mat/måltid.' },
        {
          id: 'home-eat',
          sv: 'äta mat',
          hanzi: '吃饭',
          pinyin: 'chīfàn',
          components: [
            { hanzi: '吃', pinyin: 'chī', sv: 'äta' },
            { hanzi: '饭', pinyin: 'fàn', sv: 'ris / mat' },
          ],
        },
        { id: 'home-water', sv: 'vatten', hanzi: '水', pinyin: 'shuǐ' },
        {
          id: 'home-drink-water',
          sv: 'dricka vatten',
          hanzi: '喝水',
          pinyin: 'hē shuǐ',
          components: [
            { hanzi: '水', pinyin: 'shuǐ', sv: 'vatten' },
          ],
        },
        { id: 'home-sleep-char', sv: 'sova', hanzi: '睡', pinyin: 'shuì', notesSv: 'Första tecknet i 睡觉.' },
        {
          id: 'home-sleep',
          sv: 'sova / gå och lägga sig',
          hanzi: '睡觉',
          pinyin: 'shuìjiào',
          components: [
            { hanzi: '睡', pinyin: 'shuì', sv: 'sova' },
            { hanzi: '觉', pinyin: 'jiào', sv: 'sömn' },
          ],
        },
        { id: 'home-milk-char', sv: 'mjölk', hanzi: '奶', pinyin: 'nǎi', notesSv: 'Andra tecknet i 牛奶.' },
        { id: 'home-milk', sv: 'mjölk', hanzi: '牛奶', pinyin: 'niúnǎi', components: [{ hanzi: '奶', pinyin: 'nǎi', sv: 'mjölk' }] },
      ],
    },
  ],
};
