export const homeBasics = {
  id: 'home-basics',
  titleSv: 'Hemma: grunder',
  titleZh: '家庭基础',
  pinyin: 'jiātíng jīchǔ',
  descriptionSv: 'Ord och korta fraser för familj, barn och vardag hemma.',
  order: 1,
  lessons: [
    {
      id: 'family',
      titleSv: 'Familj',
      descriptionSv: 'De första familjeorden.',
      unlocksUiKeys: [],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'home-mom', sv: 'mamma', hanzi: '妈妈', pinyin: 'māma', notesSv: 'Vanligt familjeord.' },
        { id: 'home-dad', sv: 'pappa', hanzi: '爸爸', pinyin: 'bàba' },
        { id: 'home-child', sv: 'barn', hanzi: '孩子', pinyin: 'háizi' },
        { id: 'home-wife', sv: 'fru / frun', hanzi: '老婆', pinyin: 'lǎopo', notesSv: 'Vardagligt ord för fru/hustru.' },
        { id: 'home-family', sv: 'familj', hanzi: '家人', pinyin: 'jiārén' },
      ],
    },
    {
      id: 'daily-commands',
      titleSv: 'Korta vardagsfraser',
      descriptionSv: 'Sånt man ofta säger hemma till barn.',
      unlocksUiKeys: [],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'home-come-here', sv: 'kom hit', hanzi: '过来', pinyin: 'guòlái' },
        { id: 'home-wait', sv: 'vänta lite', hanzi: '等一下', pinyin: 'děng yíxià' },
        { id: 'home-hurry', sv: 'skynda dig', hanzi: '快点', pinyin: 'kuài diǎn' },
        { id: 'home-stop', sv: 'sluta / stopp', hanzi: '停', pinyin: 'tíng' },
        { id: 'home-sit', sv: 'sitt ner', hanzi: '坐下', pinyin: 'zuò xià' },
      ],
    },
    {
      id: 'eat-drink-sleep',
      titleSv: 'Äta, dricka, sova',
      descriptionSv: 'Mycket vanliga ord hemma, med byggstenar före hela fraser.',
      unlocksUiKeys: [],
      practiceModes: ['type-pinyin'],
      items: [
        { id: 'home-eat-char', sv: 'äta', hanzi: '吃', pinyin: 'chī', notesSv: 'Första tecknet i 吃饭.' },
        { id: 'home-rice-food', sv: 'ris / mat', hanzi: '饭', pinyin: 'fàn', notesSv: 'Andra tecknet i 吃饭; kan betyda ris eller mat/måltid.' },
        {
          id: 'home-eat',
          sv: 'äta mat',
          hanzi: '吃饭',
          pinyin: 'chīfàn',
          components: [
            { hanzi: '吃', pinyin: 'chī', sv: 'äta' },
            { hanzi: '饭', pinyin: 'fàn', sv: 'ris / mat' },
          ],
        },
        { id: 'home-water', sv: 'vatten', hanzi: '水', pinyin: 'shuǐ' },
        {
          id: 'home-drink-water',
          sv: 'dricka vatten',
          hanzi: '喝水',
          pinyin: 'hē shuǐ',
          components: [
            { hanzi: '喝', pinyin: 'hē', sv: 'dricka' },
            { hanzi: '水', pinyin: 'shuǐ', sv: 'vatten' },
          ],
        },
        { id: 'home-sleep-char', sv: 'sova', hanzi: '睡', pinyin: 'shuì', notesSv: 'Första tecknet i 睡觉.' },
        {
          id: 'home-sleep',
          sv: 'sova / gå och lägga sig',
          hanzi: '睡觉',
          pinyin: 'shuìjiào',
          components: [
            { hanzi: '睡', pinyin: 'shuì', sv: 'sova' },
            { hanzi: '觉', pinyin: 'jiào', sv: 'sömn' },
          ],
        },
        { id: 'home-milk', sv: 'mjölk', hanzi: '牛奶', pinyin: 'niúnǎi', components: [{ hanzi: '奶', pinyin: 'nǎi', sv: 'mjölk' }] },
      ],
    },
  ],
};
